### ISSUE TITLE
Request for "Launchpad Mini MK3" to be added to list of launchpad port names

### ISSUE THREAD

**Issue by obeezzy** [joedeller/LPMidi#1]
I recently purchased a Launchpad Mini MK3 and discovered its MIDI port name was registered as `"Launchpad Mini MK3:Launchpad Mini MK3 MIDI 2 36:1"` on Manjaro Linux and therefore `LPMidi.find_connected_launchpad()` returns `"I couldn't find any attached launchpads. Raising IOError"`. 
Appending `"Launchpad Mini MK3"` to the list of launchpads fixes the issue
i.e. changing from this:
`self.launchpads = ['(LPMiniMK3', 'MK2',  'Launchpad MK3', 'Launchpad Pro']`
to this:
`self.launchpads = ['(LPMiniMK3', 'MK2',  'Launchpad MK3', 'Launchpad Pro', 'Launchpad Mini MK3']`.

What would be the proper way to make this change? I am willing to create a pull request if you agree with my suggestion.
Also, I can only test on Linux, so I wouldn't be able to test the `"Darwin"` if condition in `LPMidi.find_connected_launchpad()`.

**Comment by joedeller** [comment]
Hi there, I must confess I haven't run the code on Linux, ideally we'd want to extend the checks for the platform.system to include a check for Linux and put in the reported names for it.

I've only got Windows and Mac  OS with me at the moment, but if I remember correctly, this should just return "Linux",  so we would have  (ignoring we should explicitly check for Windows)

if platform.system() =="Darwin":
    self.launchpads = ['(LPMiniMK3', 'MK2', 'Launchpad MK3', 'Launchpad Pro']
elif platform.system() == "Linux":
    # Need to find the reported names for launchpads on Linux
    self.launchpads = ['Launchpad Mini MK3']
else:
    self.launchpads = ['(LPMiniMK3', 'MK2', 'Launchpad MK3', 'Launchpad Pro']

I'll setup a Linux system at some point, but perhaps you could just check that still works for you?  If so by all means create a pull request.

Thanks for your interest !
Joe

**Comment by obeezzy** [comment]
I tried to push a commit to this repo but I'm getting `X11 forwarding request failed on channel 0
ERROR: Permission to joedeller/LPMidi.git denied to obeezzy.
fatal: Could not read from remote repository.`. 

Is there something I'm doing wrong? I'm running:
`git push origin add-alternate-launchpad-port-name`
NOTE: `add-alternate-launchpad-port-name` is the name of my branch.

And yes, your change does work for me.

**Comment by joedeller** [comment]
Hi there, should be an invite for you to be able to do the push, let me know if it still doesn't work.

Thanks,

Joe

**Comment by obeezzy** [comment]
Request granted with #2 .
